services:
  database:
    build:
      context: ./postgres
    container_name: todo-app-postgres
    networks:
      - todo-app
    volumes:
      - type: volume
        source: todo-app-volume
        target: /var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5433:5432"

  flask:
    build:
      context: ./todo-app-backend
    container_name: todo-app-backend
    networks:
      - todo-app
    volumes:
      - type: bind
        source: ./todo-app-backend
        target: /app
    restart: on-failure
    depends_on:
      - database
    ports:
      - "3000:5000"

  react:
    build:
      context: ./todo-app-frontend
    container_name: todo-app-frontend
    command: sh -c "npm rebuild esbuild && yarn dev"
    networks:
      - todo-app
    volumes:
      - type: bind
        source: ./todo-app-frontend
        target: /app
    restart: on-failure
    depends_on:
      - flask
      - database
    ports:
      - "3001:5173"

volumes:
  todo-app-volume:

networks:
  todo-app:
